/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.28
 * Generated at: 2024-08-31 07:45:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.revature.service.dao.*;
import com.revature.service.*;
import com.revature.data.*;
import java.util.*;
import jakarta.servlet.ServletOutputStream;
import java.io.*;

public final class updateProduct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/footer.html", Long.valueOf(1725004106572L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(11);
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("com.revature.service");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("com.revature.service.dao");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_packages.add("com.revature.data");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("jakarta.servlet.ServletOutputStream");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Update Product</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/changes.css\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-color: #E6F9E6;\">\r\n");
      out.write("	");

	/* Checking the user credentials */
	String utype = (String) session.getAttribute("usertype");
	String uname = (String) session.getAttribute("username");
	String pwd = (String) session.getAttribute("password");
	String prodid = request.getParameter("prodid");
	ProductData product = new ProductServiceImpl().getProductDetails(prodid);
	if (prodid == null || product == null) {
		response.sendRedirect("updateProductById.jsp?message=Please Enter a valid product Id");
		return;
	} else if (utype == null || !utype.equals("admin")) {
		response.sendRedirect("login.jsp?message=Access Denied, Login as admin!!");
		return;
	} else if (uname == null || pwd == null) {
		response.sendRedirect("login.jsp?message=Session Expired, Login Again!!");
		return;
	}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");

	String message = request.getParameter("message");
	
      out.write("\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"row\"\r\n");
      out.write("			style=\"margin-top: 5px; margin-left: 2px; margin-right: 2px;\">\r\n");
      out.write("			<form action=\"./UpdateProductServlet\" method=\"post\"\r\n");
      out.write("				class=\"col-md-6 col-md-offset-3\"\r\n");
      out.write("				style=\"border: 2px solid black; border-radius: 10px; background-color: #FFE5CC; padding: 10px;\">\r\n");
      out.write("				<div style=\"font-weight: bold;\" class=\"text-center\">\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<img src=\"./ShowImage?pid=");
      out.print(product.getProdId());
      out.write("\"\r\n");
      out.write("							alt=\"Product Image\" height=\"100px\" />\r\n");
      out.write("						<h2 style=\"color: green;\">Product Update Form</h2>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					");

					if (message != null) {
					
      out.write("\r\n");
      out.write("					<p style=\"color: blue;\">\r\n");
      out.write("						");
      out.print(message);
      out.write("\r\n");
      out.write("					</p>\r\n");
      out.write("					");

					}
					
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<input type=\"hidden\" name=\"pid\" class=\"form-control\"\r\n");
      out.write("						value=\"");
      out.print(product.getProdId());
      out.write("\" id=\"last_name\" required>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"col-md-6 form-group\">\r\n");
      out.write("						<label for=\"last_name\">Product Name</label> <input type=\"text\"\r\n");
      out.write("							placeholder=\"Enter Product Name\" name=\"name\" class=\"form-control\"\r\n");
      out.write("							value=\"");
      out.print(product.getProdName());
      out.write("\" id=\"last_name\" required>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-md-6 form-group\">\r\n");
      out.write("						");

						String ptype = product.getProdType();
						
      out.write("\r\n");
      out.write("						<label for=\"producttype\">Product Type</label> <select name=\"type\"\r\n");
      out.write("							id=\"producttype\" class=\"form-control\" required>\r\n");
      out.write("							<option value=\"mobile\"\r\n");
      out.write("								");
      out.print("mobile".equalsIgnoreCase(ptype) ? "selected" : "");
      out.write(">MOBILE</option>\r\n");
      out.write("							<option value=\"tv\"\r\n");
      out.write("								");
      out.print("tv".equalsIgnoreCase(ptype) ? "selected" : "");
      out.write(">TV</option>\r\n");
      out.write("							<option value=\"camera\"\r\n");
      out.write("								");
      out.print("camera".equalsIgnoreCase(ptype) ? "selected" : "");
      out.write(">CAMERA</option>\r\n");
      out.write("							<option value=\"laptop\"\r\n");
      out.write("								");
      out.print("laptop".equalsIgnoreCase(ptype) ? "selected" : "");
      out.write(">LAPTOP</option>\r\n");
      out.write("							<option value=\"tablet\"\r\n");
      out.write("								");
      out.print("tablet".equalsIgnoreCase(ptype) ? "selected" : "");
      out.write(">TABLET</option>\r\n");
      out.write("							<option value=\"speaker\"\r\n");
      out.write("								");
      out.print("speaker".equalsIgnoreCase(ptype) ? "selected" : "");
      out.write(">SPEAKER</option>\r\n");
      out.write("							<option value=\"other\"\r\n");
      out.write("								");
      out.print("other".equalsIgnoreCase(ptype) ? "selected" : "");
      out.write(">Some\r\n");
      out.write("								Other Appliances</option>\r\n");
      out.write("						</select>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-group\">\r\n");
      out.write("					<label for=\"last_name\">Product Description</label>\r\n");
      out.write("					<textarea name=\"info\" class=\"form-control text-align-left\"\r\n");
      out.write("						id=\"last_name\" required>");
      out.print(product.getProdInfo());
      out.write("</textarea>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"col-md-6 form-group\">\r\n");
      out.write("						<label for=\"last_name\">Unit Price</label> <input type=\"number\"\r\n");
      out.write("							value=\"");
      out.print(product.getProdPrice());
      out.write("\"\r\n");
      out.write("							placeholder=\"Enter Unit Price\" name=\"price\" class=\"form-control\"\r\n");
      out.write("							id=\"last_name\" required>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-md-6 form-group\">\r\n");
      out.write("						<label for=\"last_name\">Stock Quantity</label> <input type=\"number\"\r\n");
      out.write("							value=\"");
      out.print(product.getProdQuantity());
      out.write("\"\r\n");
      out.write("							placeholder=\"Enter Stock Quantity\" class=\"form-control\"\r\n");
      out.write("							id=\"last_name\" name=\"quantity\" required>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"row text-center\">\r\n");
      out.write("					<div class=\"col-md-4\" style=\"margin-bottom: 2px;\">\r\n");
      out.write("						<button formaction=\"adminViewProduct.jsp\" class=\"btn btn-danger\">Cancel</button>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-md-4\">\r\n");
      out.write("						<button type=\"submit\" class=\"btn btn-success\">Update\r\n");
      out.write("							Product</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>ShopMart</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/changes.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-color: rgb(255, 255, 255);\">\r\n");
      out.write("	<!-- Start the footer Contacts -->\r\n");
      out.write("	<!-- <a name=\"contact\"></a> -->\r\n");
      out.write("	<div class=\"container-fluid\"\r\n");
      out.write("		style=\"background-color: #454862; color: white; margin-top: 200px;\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<h3 class=\"text-center\">Contact US!</h3>\r\n");
      out.write("			<p class=\"text-center\">\r\n");
      out.write("				<em>Thanks for visit</em>\r\n");
      out.write("			</p>\r\n");
      out.write("			<div class=\"row test\">\r\n");
      out.write("				<div class=\"col-md-4\">\r\n");
      out.write("					<p>Provide Feedback</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						<span class=\"glyphicon glyphicon-map-marker\"></span>Elas Dasalkar\r\n");
      out.write("					</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						<span class=\"glyphicon glyphicon-phone\"></span>Phone: 0223 45659\r\n");
      out.write("					\r\n");
      out.write("					</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						<span class=\"glyphicon glyphicon-envelope\"></span>Email:\r\n");
      out.write("						Revatureshop@gmail.com\r\n");
      out.write("					</p>\r\n");
      out.write("					\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-8\">\r\n");
      out.write("					<form action=\"fansMessage\" method=\"post\">\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<div class=\"col-sm-6 form-group\">\r\n");
      out.write("								<input class=\"form-control\" id=\"name\" name=\"name\"\r\n");
      out.write("									placeholder=\"Name\" type=\"text\" required>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-sm-6 form-group\">\r\n");
      out.write("								<input class=\"form-control\" id=\"email\" name=\"email\"\r\n");
      out.write("									placeholder=\"Email\" type=\"email\" required>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<textarea class=\"form-control\" id=\"comments\" name=\"comments\"\r\n");
      out.write("							placeholder=\"Comment\" rows=\"5\" required></textarea>\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<div class=\"col-md-12 form-group\">\r\n");
      out.write("								<button class=\"btn pull-right\" type=\"submit\">Send</button>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- End of Contact or about us -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
